[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=0.6.3",
    "markdownify>=0.14.1",
    "sentence-transformers>=3.4.1",
    "smolagents[litellm]>=1.8.0",
]
